# Generated by Django 5.1.7 on 2025-03-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('imagen', models.ImageField(blank=True, upload_to='categorias/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='Tienda_cate_nombre_fa2889_idx')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/%Y/%m/%d')),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('fecha_creado', models.DateField(auto_now_add=True)),
                ('fecha_modificado', models.DateField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Tienda.categoria')),
            ],
            options={
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['id', 'slug'], name='Tienda_prod_id_c93c59_idx'), models.Index(fields=['nombre'], name='Tienda_prod_nombre_fe54c1_idx'), models.Index(fields=['-fecha_creado'], name='Tienda_prod_fecha_c_f84852_idx')],
            },
        ),
    ]
