# Generated by Django 5.1.4 on 2025-03-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='envio_gratis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.CharField(choices=[('libra', 'Libra'), ('unidad', 'Unidad'), ('tamaño', 'Tamaño')], default='unidad', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='opcion_mensajeria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='rebajado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='Tienda.marca'),
        ),
    ]
