# Generated by Django 5.1.4 on 2025-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_marca_producto_envio_gratis_producto_medida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tamaño',
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
