# Generated by Django 5.1.4 on 2025-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_carrito_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='carritos', to='Tienda.producto'),
        ),
    ]
