# Generated by Django 5.1.4 on 2025-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0014_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='nueva_fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
