# Generated by Django 5.1.4 on 2025-06-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0015_entrada_nueva_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='venta_de_garaje',
            field=models.BooleanField(default=False),
        ),
    ]
