# Generated by Django 5.1.4 on 2025-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0016_producto_venta_de_garaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventatemporalitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
