# Generated by Django 5.1.4 on 2025-07-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0017_venta_total_a_pagar_alter_ventatemporalitem_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace directo de la imagen en Drive', null=True),
        ),
    ]
