# Generated by Django 5.1.4 on 2025-07-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0018_remove_categoria_imagen_categoria_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace directo de la imagen', null=True),
        ),
    ]
