# Generated by Django 5.1.4 on 2025-07-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0019_remove_producto_imagen_alter_categoria_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace directo de la imagen', null=True),
        ),
    ]
