# Generated by Django 5.1.4 on 2025-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0020_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
