# Generated by Django 5.1.4 on 2025-07-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0021_producto_precio_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='precio_venta_efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
