# Generated by Django 5.1.4 on 2025-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0022_entrada_precio_venta_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='precio_unitario_efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
