# Generated by Django 5.1.4 on 2025-07-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0023_ventaitem_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='deshabilitado',
            field=models.BooleanField(default=False, help_text='Marca este producto como deshabilitado si ya no se vende ni repone.'),
        ),
    ]
