# Generated by Django 5.1.4 on 2025-07-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0025_gasto_gastoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastoitem',
            name='gasto',
        ),
        migrations.RemoveField(
            model_name='gastoitem',
            name='producto',
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('gasto', 'Agregar a gastos'), ('cuenta_trabajador', 'Agregar a cuenta de trabajador')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
        migrations.DeleteModel(
            name='GastoItem',
        ),
    ]
