# Generated by Django 5.1.4 on 2025-07-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0026_remove_gastoitem_gasto_remove_gastoitem_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='motivo_gasto',
            field=models.TextField(blank=True, help_text='Describe el motivo si esta venta fue registrada como gasto', null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('gasto', 'Agregar a gastos')], max_length=30),
        ),
    ]
