# Generated by Django 5.1.4 on 2025-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0028_cuadre_cuadredetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadre',
            name='fecha',
            field=models.DateField(),
        ),
    ]
