# Generated by Django 5.1.4 on 2025-07-16 15:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0029_alter_cuadre_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(choices=[('error_entrada', 'Error de entrada'), ('ajuste_stock', 'Ajuste de stock')], max_length=20)),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='Tienda.producto')),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
