# Generated by Django 5.1.4 on 2025-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0030_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadredetalle',
            name='salidas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
