# Generated by Django 5.1.4 on 2025-08-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0031_cuadredetalle_salidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (0 = primero)')),
                ('url_imagen_escritorio', models.URLField(help_text='URL de la imagen para escritorio (ej: https://mi-nube.com/imagen1.jpg)', max_length=500)),
                ('url_imagen_movil', models.URLField(blank=True, help_text='URL de la imagen para móvil (opcional, si no se usa, se hereda la de escritorio)', max_length=500, null=True)),
                ('titulo', models.CharField(blank=True, help_text='Título descriptivo (para SEO)', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Mostrar esta imagen en el carrusel')),
                ('url_destino', models.URLField(blank=True, help_text='URL a la que dirige la imagen (ej: /promociones/)')),
                ('texto_boton', models.CharField(blank=True, default='Ver más', help_text='Texto del botón (solo si hay URL destino)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Imágenes del Carrusel',
                'ordering': ['orden'],
            },
        ),
    ]
